import type {
  StorageAdapter,
  GraphDiff,
  ObjectDiff,
  RelationDiff,
  GraphEvent,
  JsonValue,
} from './types.js'

/**
 * Compute the diff between two graphs by walking their event logs.
 *
 * The log is the source of truth. Instead of comparing snapshot state,
 * we walk the post-fork events on each side to determine exactly what
 * changed and how.
 *
 * For forked graphs: finds the fork point, then diffs events after it.
 * For independent graphs: all events on each side are "exclusive".
 */
export async function computeDiff(
  sourceGraphId: string,
  targetGraphId: string,
  storage: StorageAdapter
): Promise<GraphDiff> {
  // 1. Find fork point (if target was branched from source)
  const forkEvents = await storage.queryEvents(targetGraphId, {
    type: 'custom.graph_forked' as GraphEvent['type'],
  })
  const forkEvent = forkEvents.find(
    (e) => e.payload.sourceGraphId === sourceGraphId
  )

  // 2. Get all events from both graphs
  const allSourceEvents = await storage.queryEvents(sourceGraphId, {})
  const allTargetEvents = await storage.queryEvents(targetGraphId, {})

  // 3. Determine which events are post-fork (exclusive to each side)
  let sourceLog: GraphEvent[]
  let targetLog: GraphEvent[]

  if (forkEvent) {
    const eventsCopied = (forkEvent.payload.eventsCopied as number) ?? 0
    sourceLog = allSourceEvents.slice(eventsCopied)
    // Skip copied events + the graph_forked event
    targetLog = allTargetEvents.slice(eventsCopied + 1)
  } else {
    sourceLog = allSourceEvents
    targetLog = allTargetEvents
  }

  // 4. Derive object diffs from the event logs
  const objects = deriveObjectDiffs(sourceLog, targetLog)

  // 5. Derive relation diffs from the event logs
  const relations = deriveRelationDiffs(sourceLog, targetLog)

  return {
    sourceGraphId,
    targetGraphId,
    objects,
    relations,
    sourceLog,
    targetLog,
  }
}

// ─── Object Diffing ─────────────────────────────────────────────────────────

interface ObjectMutation {
  objectType?: string
  netEffect: 'created' | 'modified' | 'removed'
  finalData?: Record<string, JsonValue>
}

/**
 * Walk events to build per-object change summaries, then combine
 * source and target mutations into a unified diff.
 */
function deriveObjectDiffs(
  sourceEvents: GraphEvent[],
  targetEvents: GraphEvent[]
): ObjectDiff[] {
  const sourceMutations = extractObjectMutations(sourceEvents)
  const targetMutations = extractObjectMutations(targetEvents)
  const diffs: ObjectDiff[] = []

  // Target-side mutations (from the branch's perspective)
  for (const [id, m] of targetMutations) {
    if (m.netEffect === 'created') {
      diffs.push({ objectId: id, type: m.objectType ?? 'unknown', status: 'added', data: m.finalData })
    } else if (m.netEffect === 'removed') {
      diffs.push({ objectId: id, type: m.objectType ?? 'unknown', status: 'removed' })
    } else if (m.netEffect === 'modified') {
      diffs.push({ objectId: id, type: m.objectType ?? 'unknown', status: 'modified', targetData: m.finalData })
    }
  }

  // Source-side mutations not covered by target
  for (const [id, m] of sourceMutations) {
    if (targetMutations.has(id)) continue // Already covered above

    if (m.netEffect === 'created') {
      // Source added something the branch doesn't have
      diffs.push({ objectId: id, type: m.objectType ?? 'unknown', status: 'removed', data: m.finalData })
    } else if (m.netEffect === 'removed') {
      // Source removed something the branch still has
      diffs.push({ objectId: id, type: m.objectType ?? 'unknown', status: 'added' })
    } else if (m.netEffect === 'modified') {
      diffs.push({ objectId: id, type: m.objectType ?? 'unknown', status: 'modified', sourceData: m.finalData })
    }
  }

  return diffs
}

function extractObjectMutations(events: GraphEvent[]): Map<string, ObjectMutation> {
  const mutations = new Map<string, ObjectMutation>()

  for (const event of events) {
    if (event.type === 'object.created') {
      // object.created may not have objectId in the event payload (ID is generated by storage).
      // Use the event ID as key — objects link back via createdByEventId.
      const objectType = event.payload.objectType as string
      const data = event.payload.data as Record<string, JsonValue> | undefined
      // We use a synthetic key for created objects: "created:<eventId>"
      // This tracks the creation; patched/removed events use actual objectId.
      const key = `created:${event.id}`
      mutations.set(key, { objectType, netEffect: 'created', finalData: data })
    } else if (event.type === 'object.patched') {
      const id = event.payload.objectId as string
      const patch = event.payload.patch as Record<string, JsonValue>
      const existing = mutations.get(id)
      if (existing) {
        existing.finalData = { ...existing.finalData, ...patch }
      } else {
        mutations.set(id, { netEffect: 'modified', finalData: patch })
      }
    } else if (event.type === 'object.removed') {
      const id = event.payload.objectId as string
      // Check if this was a create-then-remove (net nothing)
      for (const [key, m] of mutations) {
        if (key.startsWith('created:') && m.netEffect === 'created') {
          // Can't match by ID since created events don't have objectId.
          // For now, removed events on known objectIds are tracked directly.
        }
      }
      mutations.set(id, { netEffect: 'removed' })
    }
  }

  return mutations
}

// ─── Relation Diffing ───────────────────────────────────────────────────────

interface RelationMutation {
  relationType?: string
  sourceId?: string
  targetId?: string
  netEffect: 'created' | 'removed'
}

function deriveRelationDiffs(
  sourceEvents: GraphEvent[],
  targetEvents: GraphEvent[]
): RelationDiff[] {
  const sourceMutations = extractRelationMutations(sourceEvents)
  const targetMutations = extractRelationMutations(targetEvents)
  const diffs: RelationDiff[] = []

  for (const [id, m] of targetMutations) {
    diffs.push({
      relationId: id,
      type: m.relationType ?? 'unknown',
      sourceId: m.sourceId ?? '',
      targetId: m.targetId ?? '',
      status: m.netEffect === 'created' ? 'added' : 'removed',
    })
  }

  for (const [id, m] of sourceMutations) {
    if (targetMutations.has(id)) continue
    diffs.push({
      relationId: id,
      type: m.relationType ?? 'unknown',
      sourceId: m.sourceId ?? '',
      targetId: m.targetId ?? '',
      // Inverted: source created → branch doesn't have it (removed from branch perspective)
      status: m.netEffect === 'created' ? 'removed' : 'added',
    })
  }

  return diffs
}

function extractRelationMutations(events: GraphEvent[]): Map<string, RelationMutation> {
  const mutations = new Map<string, RelationMutation>()

  for (const event of events) {
    if (event.type === 'relation.created') {
      const key = `created:${event.id}`
      mutations.set(key, {
        relationType: event.payload.relationType as string,
        sourceId: event.payload.sourceId as string,
        targetId: event.payload.targetId as string,
        netEffect: 'created',
      })
    } else if (event.type === 'relation.removed') {
      const id = event.payload.relationId as string
      mutations.set(id, { netEffect: 'removed' })
    }
  }

  return mutations
}
